//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ECOMMERCEEntities : DbContext
    {
        public DB_ECOMMERCEEntities()
            : base("name=DB_ECOMMERCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_CART> TB_CART { get; set; }
        public virtual DbSet<TB_CART_STATUS> TB_CART_STATUS { get; set; }
        public virtual DbSet<TB_CATEGORY> TB_CATEGORY { get; set; }
        public virtual DbSet<TB_MEMBER_ROLE> TB_MEMBER_ROLE { get; set; }
        public virtual DbSet<TB_MEMBERS> TB_MEMBERS { get; set; }
        public virtual DbSet<TB_PRODUCT> TB_PRODUCT { get; set; }
        public virtual DbSet<TB_ROLES> TB_ROLES { get; set; }
        public virtual DbSet<TB_SHIPPING_DETAILS> TB_SHIPPING_DETAILS { get; set; }
        public virtual DbSet<TB_SLIDE_IMAGE> TB_SLIDE_IMAGE { get; set; }
    }
}
