//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SLIDE_IMAGE
    {
        public int SLIDE_ID { get; set; }
        public string SLIDE_TITLE { get; set; }
        public string SLIDE_IMAGE { get; set; }
    }
}
