//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SHIPPING_DETAILS
    {
        public int SHIPPING_DETAIL_ID { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public string ADRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
    
        public virtual TB_MEMBERS TB_MEMBERS { get; set; }
    }
}
